### ISSUE TITLE
Integrate with Continuous Integration service

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-ui-default#105]
In order to run the tests during pushes or pull requests, we need to configure this package with Travis.

We need to add a file `.travis.yml`:

```yml
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install @ckeditor/ckeditor5-dev-tests
  - npm install codeclimate-test-reporter
script:
  - node_modules/.bin/ckeditor5-dev-tests --coverage
after_success:
  - node_modules/.bin/codeclimate-test-reporter < .build/coverage/lcov.info
```

Also need to fill `dependencies` and `devDependencies` in `package.json`.

For this package it will be:

```json
"dependencies": {
    "ckeditor5-ui": "ckeditor/ckeditor5-ui",
    "ckeditor5-theme-lark": "ckeditor/ckeditor5-theme-lark",
    "ckeditor5-utils": "ckeditor/ckeditor5-utils"
}
```
